apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-to-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-to-start
  template:
    metadata:
      labels:
        app: spark-to-start
    spec:
      containers:
        - name: spark-to-start
          image: apache/spark-py:v3.4.0
          env:
            - name: PATH
              value: "/opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo [INFO] Source code
              cat /app/features.py
              spark-submit --version
              spark-submit /app/features.py
              tail -f /dev/null
          volumeMounts:
            - name: features-script
              mountPath: /app/features.py
              subPath: features.py
      volumes:
        - name: features-script
          configMap:
            name: pyspark-config
      securityContext:
        runAsUser: 0 # temporary solution to execute spark-submit. Error: Exception in thread "main" java.lang.IllegalArgumentException: basedir must be absolute: ?/.ivy2/local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-legacy
  template:
    metadata:
      labels:
        app: spark-legacy
    spec:
      containers:
        - name: spark-legacy
          image: apache/spark-py:v3.2.4
          env:
            - name: PATH
              value: "/opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo [INFO] Source code
              cat /app/features.py
              spark-submit --version
              spark-submit /app/features.py
              tail -f /dev/null
          volumeMounts:
            - name: features-script
              mountPath: /app/features.py
              subPath: features.py
      volumes:
        - name: features-script
          configMap:
            name: pyspark-config
      securityContext:
        runAsUser: 0 # temporary solution to execute spark-submit. Error: Exception in thread "main" java.lang.IllegalArgumentException: basedir must be absolute: ?/.ivy2/local
