# Default values for spark_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: apache/spark-py
  currentTag: "v3.4.0"
  legacyTag: "v3.2.4"

securityContext:
  runAsUser: 0

# Additional volumes on the output Deployment definition.
volumes:
  - name: features-script
    configMap:
      name: pyspark-config
      
volumeMounts:
  - name: features-script
    mountPath: /app/features.py
    subPath: features.py

legacyDeployment: spark-legacy

currentDeployment: spark-to-start
